### ISSUE TITLE
Switch to github actions

### ISSUE THREAD

**Issue by jscancella** [jscancella/bagging#39]
Instead of using multiple CI/CD providers look into using github actions.
Need to build on Windows (7, 8,  and 10 preferably), linux (ubuntu latest preferably), and Mac os. 
Need to test various versions of Java (8, 9, 10, 11, 12, 13, 14, etc.)
Only 1 of these tests need to upload coverage results to our coverage provider (coveralls.io).

**Comment by jscancella** [comment]
untested, but should get you started:
```
name: Bagging CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
  strategy:
    matrix:
    os: [windows-2019, macos-10.15, ubuntu-18.04]
    java: [8, 9, 10, 11, 12, 13]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run all the checks
      run: ./gradlew check dependencyCheckUpdate dependencyCheckAnalyze --no-daemon
    - name: upload reports
      run: ./gradlew coveralls --no-daemon
```
